plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/oxo/Library/CloudStorage/Dropbox-studionin/studionin/document/클로드_프로젝트/포트폴리오/studionin-portfolio/dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]